> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# NumPy


### Five functions from the NumPy

NumPy stands for numerical python. It helps us perform different tasks which otherwise would have beend difficult.
- insert : insert values along the given axis before the given indices.
- linespace : this function returns number spaces 
- flip : Used for reversing the array
- shape : gives shape of the array
- split : used for splitting the array

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [4]:
!pip install jovian --upgrade -q

In [5]:
import jovian

In [6]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prasadposture121/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/prasadposture121/numpy-array-operations


'https://jovian.ai/prasadposture121/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [7]:
import numpy as np

In [8]:
# List of functions explained 
function1 = np.insert
function2 = np.linspace
function3 = np.flip
function4 = np.shape
function5 = np.split

## Function 1 - np.insert
Insert values along the given axis before the given indices.

In [9]:
# Example 1 - inserting a column index 2 containing 1's
arr1 = [[1, 2], 
        [3, 4.]]
np.insert(arr1, 2, 1, axis=1)

array([[1., 2., 1.],
       [3., 4., 1.]])

A new column with values (1, 1) has been inserted at the end.

In [13]:
# Example 2 - inserting a row index 1 containing 5's
np.insert(arr1, 1, 5, axis=0)

array([[1., 2.],
       [5., 5.],
       [3., 4.]])

a new row has been added at the index 1

In [18]:
# Example 3 - we could add column at index 2 when there was nothing there at 2
#lets see if we could add column at index 3
arr1 = [[1, 2], 
        [3, 4.]]
np.insert(arr1, 3, 1, axis=1)

IndexError: index 3 is out of bounds for axis 1 with size 2

for previous example, since the 2 was the immediate next indices it could easily create a new column there, but it couldn't do the same here since the column with index 2 would have still been empty because it doesn't get replaced with zero.

Therefore this function should be used to insert new rows and columns either between the given indices or at the end.

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prasadposture121/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/prasadposture121/numpy-array-operations


'https://jovian.ai/prasadposture121/numpy-array-operations'

## Function 2 - np.linspace
 this function returns number which are equally spaced and the spacing depends upon starting and the endpoint.

In [20]:
# Example 1 - We will create an array that contains 7 equally spaced numbers from 3 to 6
np.linspace(3, 6, num=7)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

the numbers star from 3 and end at 6 in between we have 5 numbers making sure that there are total 7 equally spaced numbers as we needed

In [22]:
# Example 2 - creating array of equally spaced numbers where the endpoint isn't considered.
np.linspace(2, 4, num=9, endpoint=False)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778])

we have gotten an array with equally spaced numbers but the endpoint hasn't been considered here while dividing

In [35]:
# Example 3 - 
np.linspace(1, 4.5, num=9, endpoint=False)
#works fine

array([1.        , 1.38888889, 1.77777778, 2.16666667, 2.55555556,
       2.94444444, 3.33333333, 3.72222222, 4.11111111])

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [36]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prasadposture121/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/prasadposture121/numpy-array-operations


'https://jovian.ai/prasadposture121/numpy-array-operations'

## Function 3 - np.flip
Used for reversing the array

In [41]:
# Example 1 - reversing the numpy array given below
a=np.array([12,23,32])
np.flip(a)

array([32, 23, 12])

reverses the array `a`.

In [42]:
# Example 2 - reversing 2d numpy array
a=np.array([[12,23,32],[98,54,67]])
np.flip(a)

array([[67, 54, 98],
       [32, 23, 12]])

reverses the 2d array

In [47]:
# Example 3 - reversing 4d array
a=np.array([[12,23,32],[98,54,67],[12,39,78],[0,6,9]])
np.flip(a)
#works fine

array([[ 9,  6,  0],
       [78, 39, 12],
       [67, 54, 98],
       [32, 23, 12]])

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prasadposture121/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/prasadposture121/numpy-array-operations


'https://jovian.ai/prasadposture121/numpy-array-operations'

## Function 4 - np.shape
gives shape of the array

In [49]:
# Example 1 - getting shape of the 2d array
a=np.array([[12,23,32],[98,54,67]])
a.shape

(2, 3)

gives the shape of the array

In [52]:
# Example 2 - getting shape of the 3d array
a=np.array([[[12,23,32],[98,54,67]],[[12,39,78],[0,6,9]]])
a.shape

(2, 2, 3)

gives the shape of the array

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
# unbreakable

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prasadposture121/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/prasadposture121/numpy-array-operations


'https://jovian.ai/prasadposture121/numpy-array-operations'

## Function 5 - np.split
 used for splitting the array

In [56]:
# Example 1 - splitting the array into 2
a=np.array([[[12,23,32],[98,54,67]],[[12,39,78],[0,6,9]]])
np.split(a,2)

[array([[[12, 23, 32],
         [98, 54, 67]]]),
 array([[[12, 39, 78],
         [ 0,  6,  9]]])]

splits the array into two arrays

In [59]:
# Example 2 - splitting the array into 4
a=np.array([[12,23,32],[98,54,67],[12,39,78],[0,6,9]])
np.split(a,4)

[array([[12, 23, 32]]),
 array([[98, 54, 67]]),
 array([[12, 39, 78]]),
 array([[0, 6, 9]])]

splits the 1d array into 2

In [60]:
# Example 3 - breaking the 2d array into 4
a=np.array([[[12,23,32],[98,54,67]],[[12,39,78],[0,6,9]]])
np.split(a,4)

ValueError: array split does not result in an equal division

we can't break 2d array into  arrays

we should choose the number breaks based on the dimensions.

In [61]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prasadposture121/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/prasadposture121/numpy-array-operations


'https://jovian.ai/prasadposture121/numpy-array-operations'

## Conclusion
In this notebook we have covered different methods used with numpy array. Using these methods makes all the task easy.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [62]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "prasadposture121/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/prasadposture121/numpy-array-operations


'https://jovian.ai/prasadposture121/numpy-array-operations'